spring.application.name=rrhh

spring.datasource.url=jdbc:mysql://localhost:3306/db_rrhh
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html


# Perfil para ejecutar DataLoader
spring.profiles.active=dev






