server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: colaboradores-service
              uri: lb://ColaboradoresSucursales
              predicates:
                - Path=/api/v1/colaboradores/**, /api/v2/colaboradores/**, /ColaboradoresSucursales/api-docs/**
            
            - id: laborales-service
              uri: lb://laborales
              predicates:
                - Path=/api/v1/laborales/**, /laborales/api-docs/**
            
            - id: rrhh-service
              uri: lb://rrhh
              predicates:
                - Path=/api/v1/areas/**, /api/v1/tipos-contrato/**, /rrhh/api-docs/**

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: Microservicio ColaboradoresSucursales
        url: /ColaboradoresSucursales/api-docs
      - name: Microservicio laborales
        url: /laborales/api-docs
      - name: Microservicio rrhh
        url: /rrhh/api-docs
  api-docs:
    enabled: true
