spring.application.name=ColaboradoresSucursales
spring.profiles.active=dev

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

spring.datasource.url=jdbc:mysql://localhost:3306/db_colab_suc
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always




spring.autoconfigure.exclude=org.springdoc.core.configuration.SpringDocHateoasConfiguration