server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: colaboradores-service
              uri: lb://ColaboradoresSucursales
              predicates:
                - Path=/api/v1/colaboradores/**